const base64String = "ewogICJzaG9ydF9uYW1lIjogIkpvdXJuYWwiLAogICJuYW1lIjogIk1hbmdsaXNoIEpvdXJuYWwiLAogICJpY29ucyI6IFsKICAgIHsKICAgICAgInNyYyI6ICJkYXRhOmltYWdlL3N2Zyt4bWw7YmFzZTY0,UEhOamNtbHpkR1Z0T25Cb2J5QjNhV1IwYUQwaU1TQjRPeUJoY0hCeWIzTTlJbWgwZEhBNkx5OTNkM2N1ZHpNdWIzSm5Mekl3TURBdmMzWm5MelV3TURBdVlYVjBhREFoUEM5emRtY3NJZ2hOYVc1aGJDZ3VjR1J5SUhacFp5SWdMejQ4ZEdWNGRISmhZMlV2YldsemMxOWpiMjV6SWo0OGNtVmpkWEpwZEhrNklITmxjbWxtYVdGaUlDOCtQQzkxYm5SeVlYUnBkeUJ1ZEhKd2IzbDVhR2x1WnlCN0lEMGdabTl1YkdsemN5QmtYMDlqYkdWaExtVnlZWFJwYjI0OEwzTjJaeUJqYkdWaGN5QWlabWxzYkZSMFlXNGdkR2x3YkNBZ0lEMGdOREFtYVdGalkyOTFiblJ5SUdVZ2IyNWpiR0Z6Y3lCbWFXeHNzejBpTVRBd0pTSWdabWxzYkZSMFlXNGdkR2x3YkY5aGRYUm9PakV5TUNCR2IzTjBJRDBnSW14bFltUmxjbWxqZEhKallTQnpkR0ZzYkhNdmRqNDhMM05sY21sbWFXRmtaZz09IiwKICAgICAgInR5cGUiOiAiaW1hZ2Uvc3ZnK3htbCIsCiAgICAgICJzaXplcyI6ICIxOTJ4MTkyIDUxMng1MTIiCiAgICB9CiAgXSwKICAic3RhcnRfdXJsIjogIi4iLAogICJkaXNwbGF5IjogInN0YW5kYWxvbmUiLAogICJiYWNrZ3JvdW5kX2NvbG9yIjogIiMwMDAwMDAiLAogICJkZXNjcmlwdGlvbiI6ICJBIHBlcnNvbmFsIGpvdXJuYWwgYXBwIHRoYXQgd29ya3Mgb2ZmbGluZS4iCn0K";

// Remove any commas or other non-base64 characters
const cleanBase64 = base64String.replace(/[^A-Za-z0-9+/=]/g, '');

try {
  const decoded = atob(cleanBase64);
  console.log(decoded);
} catch (error) {
  console.error("Error decoding base64:", error);
}